name: Compile the offline installation package

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      cosVersion:
        description: cos version
        type: choice
        options:
          - latest
          - beta
        default: latest
  release:
    types: [published]

jobs:
  package-zip-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Tar gz file
        run: |
          chmod +x script/package.sh
          if [[ "${{ github.event_name }}" == "release" ]]; then
            script/package.sh --cos_version=latest --release_version=${{ github.ref_name }} --output_dir=$GITHUB_WORKSPACE --verbose
          else
            script/package.sh --cos_version=${{ inputs.cosVersion }} --output_dir=$GITHUB_WORKSPACE --verbose
          fi

      - name: Upload Tar gz file
        uses: tvrcgo/oss-action@master
        with:
          key-id: ${{ secrets.OSS_ARTIFACTS_ACCESS_KEY }}
          key-secret: ${{ secrets.OSS_ARTIFACTS_ACCESS_SECRET }}
          region: oss-cn-hangzhou
          bucket: coscene-download
          assets: |
            /home/runner/work/edge-software/edge-software/cos_binaries.tar.gz:/cosbinary/tar/${{ inputs.cosVersion }}/cos_binaries.tar.gz

      - name: Upload to S3
        run: |
          aws s3 cp $GITHUB_WORKSPACE/cos_binaries.tar.gz s3://coscene-download/cosbinary/tar/${{ inputs.cosVersion }}/cos_binaries.tar.gz
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ARTIFACTS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ARTIFACTS_ACCESS_SECRET }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cos_binaries_${{ inputs.cosVersion }}
          path: /home/runner/work/edge-software/edge-software/cos_binaries.tar.gz
          retention-days: 30
